# Generated by Django 4.0.2 on 2022-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_alter_project_options_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feautured_image',
            field=models.ImageField(blank=True, default='default.jgp', null=True, upload_to=''),
        ),
    ]
