# Generated by Django 4.0.2 on 2022-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feautured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feautured_image',
            field=models.ImageField(blank=True, default='images/default.jgp', null=True, upload_to=''),
        ),
    ]
