# Generated by Django 4.0.2 on 2022-03-05 05:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_feautured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feautured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
